name: ICPC team reference compilation
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Compiling team reference document
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your repository code
      
    - name: printing current directory
      run: ls
      
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: compilation
      run: make all

