name: ICPC team reference compilation
on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger this workflow

jobs:
  build:
    name: Compiling team reference document
    runs-on: ubuntu-latest

    steps:
    - name: printing current directory
      run: ls

    - name: compilation
      run: make all

