name: ICPC team reference compilation
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Compiling team reference document
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your repository code
      
    - name: printing current directory
      run: ls
    - name: Set up Python2.7
      uses: actions/setup-python@v4
      id: setup-python2
      with:
        python-version: 2.7
        update-environment: false

    - name: compilation
      run: make all

