name: ICPC team reference compilation
run-name: Compiling team reference document
on: [push]
runs-on: ubuntu-latest

steps:
- name: printing current directory
run: ls
- name: compilation
run: make all
